version: '3.8'

services:
  polarisstudio:
    build:
      context: .
      dockerfile: Dockerfile
    image: polarisstudio
    container_name: polarisstudio
    ports:
      - "1009:1009"  # API server
      - "8001:8001"  # Model server ports (individual mapping)
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
      - "8005:8005"
    volumes:
      - ./cache:/root/.cache  # Cache model weights
      - ./logs:/app/logs      # Logs directory
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
